scrapeIMDB/main/routes.py
from flask import render_template, request, Blueprint, g, redirect, url_for, session
from scrapeIMDB.models import Movie
from scrapeIMDB.movies.forms import SearchForm
from scrapeIMDB.config import Config
from scrapeIMDB.movies.utils import delete_upload_source
from scrapeIMDB import create_app

main = Blueprint('main', __name__)
app = create_app()


@main.before_app_request
def before_request():
    g.search_form = SearchForm()


@main.route('/')
@main.route('/home')
def home():
    file = request.args.get('file')
    if file:
        # delete needs to occur from result of redirect from create New Movie
        app.logger.debug(f'File to delete {file}')
        delete_upload_source(file, app)
        session.pop('FileName', None)

    page = request.args.get('page', 1, type=int)
    movies = Movie.query.order_by(Movie.rating.desc(), Movie.title.desc()).paginate(page=page, per_page=10)
    # movies = Movie.query.order_by(Movie.title.asc()).paginate(page=page, per_page=100)
    return render_template('home.html', movies=movies)


@main.route('/about')
def about():
    return render_template('about.html', title='About')


@main.route('/search')
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.home'))
    page = request.args.get('page', 1, type=int)
    movies, total = Movie.search(g.search_form.q.data, page,
                                 Config.MOVES_PER_PAGE)
    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * Config.MOVES_PER_PAGE else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title='Search', movies=movies,
                           next_url=next_url, prev_url=prev_url)

scrapeIMDB/movies/routes.py
import os
import traceback

from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, session, make_response, jsonify)
from flask_login import current_user, login_required

from scrapeIMDB import db, create_app
from scrapeIMDB.config import Config
from scrapeIMDB.models import Movie
from scrapeIMDB.movies.forms import UpdateMovieForm
from scrapeIMDB.movies.utils import (convert, get_files, create_movie,
                                     get_movie_file_path_list, save_movie_file,
                                     delete_upload_source)

movies = Blueprint('movies', __name__)
app = create_app()


@movies.route('/movie/new', methods=['GET', 'POST'])
@login_required
def new_movie():
    if request.method == 'POST':
        file = request.files['file']
        session["FileName"] = file.filename
        res = make_response(jsonify({"message": "File uploaded"}), 200)
        app.logger.debug(f'file name is in Session object  = {session["FileName"]}')
        if file:
            files = get_movie_file_path_list(file.filename)
            app.logger.debug(f'file path = {files[0]}')
            created = create_movie(files[0], app, True, file)
            if created:
                flash(f'Your movie has been uploaded!', 'success')
                app.logger.debug(f'The movie was uploaded successfully.')

                return redirect(url_for('main.home', file=session["FileName"], res=res))
            else:
                app.logger.debug(f'Unable to upload movie.')
                flash(f'Your movie file was not uploaded!', 'danger')

    return render_template('create_movie.html', title='New Movie')


@movies.route('/movie/<int:movie_id>')
def movie(movie_id):
    _movie = Movie.query.get_or_404(movie_id)
    running_time = convert(_movie.runtime * 60)
    actor_list = _movie.actors.split(',')
    actors = ', '.join(map(str, actor_list[0:11]))

    return render_template("movie.html", title=_movie.title, movie=_movie, running_time=running_time,
                           actors=actors)


@movies.route('/movie/<int:movie_id>/update', methods=['GET', 'POST'])
@login_required
def update_movie(movie_id):
    _movie = Movie.query.get_or_404(movie_id)
    if _movie.author != current_user:
        app.logger.warning(f'The user {session["username"]} is not authenticated to update film title {_movie.title}.')
        abort(403)
    form = UpdateMovieForm()
    if form.validate_on_submit():
        _movie.file_path = form.file_path.data
        _movie.title = form.title.data
        _movie.year = form.year.data
        _movie.genre = form.genre.data
        _movie.rating = form.rating.data
        _movie.actors = form.actors.data
        _movie.directors = form.directors.data
        _movie.writers = form.writers.data
        _movie.plot = form.plot.data
        _movie.runtime = form.runtime.data
        _movie.poster_url = form.poster_url.data
        db.session.commit()
        flash(f'Your movie has been updated!', 'success')
        app.logger.debug(f'The movie titled {_movie.title} was updated successfully.')
        return redirect(url_for('movies.movie', movie_id=_movie.id))
    elif request.method == 'GET':
        form.file_path.data = _movie.file_path
        form.title.data = _movie.title
        form.year.data = _movie.year
        form.genre.data = _movie.genre
        form.rating.data = _movie.rating
        form.actors.data = _movie.actors
        form.directors.data = _movie.directors
        form.writers.data = _movie.writers
        form.plot.data = _movie.plot
        form.runtime.data = _movie.runtime
        form.poster_url.data = _movie.poster_url
    return render_template('update_movie.html', title='Update Movie',
                           form=form, legend='Update Movie')


@movies.route('/movie/<int:movie_id>/delete', methods=['POST'])
@login_required
def delete_movie(movie_id):
    _movie = Movie.query.get_or_404(movie_id)
    if _movie.author != current_user:
        abort(403)
    file = _movie.file_path
    try:
        os.remove(file)
        db.session.delete(_movie)
        db.session.commit()
        flash(f'Your movie is deleted!', 'success')
        app.logger.debug(f'The movie, {_movie.title} was deleted successfully!')
    except OSError as e:
        flash(f'Error: {e.filename} - {e.strerror}', 'danger')
        # remove the db record even if the file does not exist in file system
        app.logger.error(
            f'The movie titled,"{_movie.title}" was deleted successfully however the file does not exist')
        db.session.delete(_movie)
        db.session.commit()
        flash(f'Your movie is deleted!', 'success')
    finally:
        return redirect(url_for('main.home'))


@movies.route('/movie/scrape')
@login_required
def scrape_imdb():
    counter = 0
    # TODO: create a Configuration model for this and other configurable types then obtain this
    #  from db instead of hardcoded
    file_sources = [Config.FLAT_FILE_SOURCE, Config.COLLECTIONS_FILE_SOURCE]
    try:
        app.logger.debug(f'Starting IMDB scrape.')
        for src in file_sources:
            file_collection = get_files(src)
            for f in file_collection:
                create_movie(f, app, False, None)
        app.logger.debug(f'Ending IMDB scrape.')
        return redirect(url_for('main.home'))
    except Exception as err:
        app.logger.error(''.join(traceback.format_exception(etype=type(err), value=err, tb=err.__traceback__)))
        flash(f'Scraping your movie folders resulted in an error try later!', 'success')
        return redirect(url_for('main.home'))


@movies.route('/movie/player/<int:movie_id>')
def movie_player(movie_id):
    _movie = Movie.query.get_or_404(movie_id)
    return render_template('movie_player.html', movie=_movie, title=_movie.title, )

scrapeIMDB/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, session
from flask_login import login_user, current_user, logout_user, login_required
from scrapeIMDB import db, bcrypt, create_app
from scrapeIMDB.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                    RequestResetForm, ResetPasswordForm)
from scrapeIMDB.models import User, Movie
from scrapeIMDB.users.utils import send_reset_email, save_picture

users = Blueprint('users', __name__)
app = create_app()


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        try:
            db.session.add(user)
        except Exception as err:
            app.logger.error(f'Error in attempting to register user {form.username.data} {err}.')
        else:
            db.session.commit()
            flash(f'Your account has now been created! You are now able to login.', 'success')
            return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            session["username"] = user.username
            next_page = request.args.get('next')
            app.logger.debug(f'User - { session["username"]} successfully logged in.')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            app.logger.warning(f'User with email address - {form.email.data} unsuccessfully tried to log-in.')
            flash(f'Login was unsuccessful! Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    if session["username"]:
        app.logger.debug(f'User - {session["username"]} logged out.')
        session.pop("username", None)
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        app.logger.debug(f'Picture file name - {current_user.image_file}.')
        db.session.commit()
        flash(f'Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_movies(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    movies = Movie.query.filter_by(author=user) \
        .order_by(Movie.rating.desc(), Movie.title.desc()) \
        .paginate(page=page, per_page=10)
    return render_template('user_movies.html', movies=movies, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password with instructions.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an expired or invalid token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been changed. Please login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

scrapeIMDB/templates/about.html
    {% extends "base.html" %}
    {% block content %}
        <h1>About Page</h1>
    {% endblock content %}

scrapeIMDB/templates/account.html
    {% extends "base.html" %}
    {% block content %}
       <div class="content-section">
          <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
              <h2 class="account-heading">{{ current_user.username }}</h2>
              <p class="text-secondary">{{ current_user.email }}</p>
            </div>
  </div>
  <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                         {% for error in form.picture.errors %}
                    <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
</div>
    {% endblock content %}

scrapeIMDB/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% if title %}
        <title>Mega Movie Listing - {{ title }}</title>
    {% else %}
        <title>Mega Movie Listing</title>
    {% endif %}

    <link rel="stylesheet"  type="text/css" href="{{url_for('static',filename='main.css') }}">
    <link href="https://vjs.zencdn.net/7.8.2/video-js.css" rel="stylesheet" />
</head>
<body>
<header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Mega Movie Listing</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('movies.new_movie') }}">New Movie</a>
                    <a class="nav-item nav-link" href="{{ url_for('movies.scrape_imdb') }}">Scraper</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                     <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
</header>

<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
      {% block content %}{% endblock %}
    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Movies</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>

 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

scrapeIMDB/templates/base_no_search.html
<!DOCTYPE html>
<html lang="en">
<head>
 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% if title %}
        <title>Mega Movie Listing - {{ title }}</title>
    {% else %}
        <title>Mega Movie Listing</title>
    {% endif %}

    <link rel="stylesheet"  type="text/css" href="{{url_for('static',filename='main.css') }}">
    <link href="https://vjs.zencdn.net/7.8.2/video-js.css" rel="stylesheet" />
</head>
<body>
<header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Mega Movie Listing</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('movies.new_movie') }}">New Movie</a>
                    <a class="nav-item nav-link" href="{{ url_for('movies.scrape_imdb') }}">Scraper</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                     <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
</header>

<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
      {% block content %}{% endblock %}
    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Movies</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>

 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

scrapeIMDB/templates/create_movie.html
    {% extends "base.html" %}
    {% block content %}

    <div class="container">
    <div class="row">
      <div class="col">

        <div class="mb-3 mt-3">

          <h2 class="mb-3" style="font-weight: 300">Upload Movie</h2>

          <div class="form-group mb-3">
            <div class="custom-file">
              <input type="file" class="custom-file-input" name="file_input" id="file_input" oninput="input_filename();">
              <label id="file_input_label" class="custom-file-label" for="image">Select file</label>
            </div>
          </div>

          <button onclick="upload('{{ request.url }}');" id="upload_btn" class="btn btn-primary">Upload</button>

          <button class="btn btn-primary d-none" id="loading_btn" type="button" disabled>
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Uploading...
          </button>

          <button type="button" id="cancel_btn" class="btn btn-secondary d-none">Cancel upload</button>

        </div>

        <div id="progress_wrapper" class="d-none">
          <label id="progress_status"></label>
          <div class="progress mb-3">
            <div id="progress" class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>

        <div id="alert_wrapper"></div>

      </div>
    </div>
  </div>
    <script src="{{url_for('static', filename='js/upload.js') }}"></script>
    {% endblock content %}

scrapeIMDB/templates/movie.html
    {% extends "base.html" %}
    {% block content %}
        <article class="media content-section">
            <img class="img-responsive mt-4 mr-4" src="{{ movie.poster_url }}" alt="{{movie.title}}">          <div class="media-body">
            <div class="article-metadata">
                 <a class="mr-2" href="#">Year - {{ movie.year }} Rating - {{ movie.rating}}</a>
                {% if movie.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('movies.movie_player', movie_id=movie.id) }}">Play It</a>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('movies.update_movie', movie_id=movie.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
                {% endif %}
            </div>
                <h2 class="article-title">{{ movie.title }}</h2>
                <p class="article-content"><b>Genre:</b> {{ movie.genre }}</p>
                <p class="article-content"><b>Plot:</b> {{ movie.plot }}</p>
                <p class="article-actors"><b>Actors:</b> {{ actors }}</p>
                <p class="article-content"><b>Directors:</b> {{ movie.directors }}</p>
                <p class="article-content"><b>Written by:</b> {{ movie.writers }}</p>
                <p class="article-content"><b>Running time:</b> {{ running_time }}</p>
                <i>Added by <a class="mr-2" href="{{ url_for('users.user_movies',username=movie.author.username) }}">{{ movie.author.username }}</a>, On <small class="text-muted">{{ movie.last_updated.strftime('%Y-%m-%d') }}</small></i>
          </div>
        </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Movie?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('movies.delete_movie',movie_id=movie.id) }}" method="POST">
                <input type="submit" class="btn btn-danger" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endblock content %}

scrapeIMDB/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Password Reset</legend>
               <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
             </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

scrapeIMDB/templates/user_movies.html
    {% extends "base.html" %}
    {% block content %}
        <h1 class="mb-3">Movies by {{ user.username }} ({{ movies.total }})</h1>
        {% for movie in movies.items %}
            <article class="media content-section">
                <a href="{{ url_for('movies.movie_player', movie_id=movie.id) }}"><img class="img-responsive mt-4 mr-4" src={{movie.poster_url }} alt="{{movie.title}}"></a>
              <div class="media-body">
                <div class="article-metadata">
                     <a class="mr-2" href="#">{{ movie.year }} Rating - {{ movie.rating}} </a>
                </div>
                <h2><a class="article-title" href="{{ url_for('movies.movie', movie_id=movie.id) }}">{{ movie.title }}</a></h2>
                <p class="article-content">{{ movie.plot }}</p>
                  <small class="text-muted">Added by <a class="mr-2" href="{{ url_for('users.user_movies',username=movie.author.username) }}">{{ movie.author.username }}</a>, on {{ movie.last_updated.strftime('%Y-%m-%d') }}</small>
              </div>
            </article>
        {% endfor %}
         {% for page_num in movies.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if movies.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_movies', username=user.username,  page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_movies', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% endblock content %}